//
//  Work_record+CoreDataProperties.swift
//  BeetClock_A1
//
//  Created by user on 10/1/16.
//  Copyright © 2016 BeetWorks. All rights reserved.
//
//  Choose "Create NSManagedObject Subclass…" from the Core Data editor menu
//  to delete and recreate this implementation file for your updated model.
//

import Foundation
import CoreData

extension Work_record {
//Removed ? optional designator from ALL
    @NSManaged var workers: NSNumber
    //@NSManaged var ms_worked: NSNumber
    @NSManaged var ms_worked: Double
    @NSManaged var timestamp: Double
    @NSManaged var notes: String
    
    //Autogenerated as NSManagedObject rather than Crop
    @NSManaged var cropRelate: Crop
    @NSManaged var jobRelate: Job
    @NSManaged var equipRelate: Equipment
    @NSManaged var tractorRelate: Tractor

}
